name: Build for ARM64
on: 
  push:
    paths:
      - '**.go'
      - '**.yaml'
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v2
      - name: Build
        run: |
          CGO_ENABLED=1 GOOS=linux GOARCH=arm64 go build -v -o out/move_srt
      # - name: Set Release env
      #   run: |
      #     echo "${{secrets.GITHUB_TOKEN}}" > ~/.ssh/id_rsa
      #     chmod 600 ~/.ssh/id_rsa
      #     ssh-keyscan github.com >> ~/.ssh/known_hosts
      #     git config --global user.email "whitemailg@gmail.com"
      #     git config --global user.name "white"
      - name: Create Release With Asset
        uses: Hs1r1us/Release-AIO@v1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          asset_files: './out/*'

