name: Build for ARM64
on: 
  push:
    paths:
      - '**.go'
      - '**.yaml'
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v2
      - name: Build
        run: |
          CGO_ENABLED=1 GOOS=linux GOARCH=arm64 go build -v -o out/move_srt
      - name: Release
        uses: elgohr/Github-Release-Action@master
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          args: Auto Release

